/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { ActividadesHorarioUbicacionListItem } from './models/ActividadesHorarioUbicacionListItem';
export type { ActividadesHorarioUbicacionListResponse } from './models/ActividadesHorarioUbicacionListResponse';
export type { ActividadesListItem } from './models/ActividadesListItem';
export type { ActividadesListResponse } from './models/ActividadesListResponse';
export type { ActividadesPorZonaListItem } from './models/ActividadesPorZonaListItem';
export type { ActividadesPorZonaListResponse } from './models/ActividadesPorZonaListResponse';
export type { ApartadosBoletoDestinatarioListItem } from './models/ApartadosBoletoDestinatarioListItem';
export type { ApartadosBoletoDestinatarioListResponse } from './models/ApartadosBoletoDestinatarioListResponse';
export type { ApartadosDeBoletoListItem } from './models/ApartadosDeBoletoListItem';
export type { ApartadosDeBoletoListResponse } from './models/ApartadosDeBoletoListResponse';
export type { ArticulosAdicionalListItem } from './models/ArticulosAdicionalListItem';
export type { ArticulosAdicionalListResponse } from './models/ArticulosAdicionalListResponse';
export type { AsientosListItem } from './models/AsientosListItem';
export type { AsientosListResponse } from './models/AsientosListResponse';
export type { BoletosListItem } from './models/BoletosListItem';
export type { BoletosListResponse } from './models/BoletosListResponse';
export type { CanalesDeVentaListItem } from './models/CanalesDeVentaListItem';
export type { CanalesDeVentaListResponse } from './models/CanalesDeVentaListResponse';
export type { CarritosAdicionalListItem } from './models/CarritosAdicionalListItem';
export type { CarritosAdicionalListResponse } from './models/CarritosAdicionalListResponse';
export type { CarritosDeCompraListItem } from './models/CarritosDeCompraListItem';
export type { CarritosDeCompraListResponse } from './models/CarritosDeCompraListResponse';
export type { CarritosDeDetalleListItem } from './models/CarritosDeDetalleListItem';
export type { CarritosDeDetalleListResponse } from './models/CarritosDeDetalleListResponse';
export type { CommandResult } from './models/CommandResult';
export type { CreateActividadHorarioUbicacionRequest } from './models/CreateActividadHorarioUbicacionRequest';
export type { CreateActividadPorZonaRequest } from './models/CreateActividadPorZonaRequest';
export type { CreateActividadRequest } from './models/CreateActividadRequest';
export type { CreateApartadoBoletoDestinatarioRequest } from './models/CreateApartadoBoletoDestinatarioRequest';
export type { CreateApartadoDeBoletoRequest } from './models/CreateApartadoDeBoletoRequest';
export type { CreateArticuloAdicionalRequest } from './models/CreateArticuloAdicionalRequest';
export type { CreateAsientoRequest } from './models/CreateAsientoRequest';
export type { CreateBoletoRequest } from './models/CreateBoletoRequest';
export type { CreateCarritoAdicionalRequest } from './models/CreateCarritoAdicionalRequest';
export type { CreateCarritoDeCompraRequest } from './models/CreateCarritoDeCompraRequest';
export type { CreateCarritoDeDetalleRequest } from './models/CreateCarritoDeDetalleRequest';
export type { CreateCuponDePromocionRequest } from './models/CreateCuponDePromocionRequest';
export type { CreateEventoRequest } from './models/CreateEventoRequest';
export type { CreateMesaRequest } from './models/CreateMesaRequest';
export type { CreatePrecioDeBoletoRequest } from './models/CreatePrecioDeBoletoRequest';
export type { CreatePromocionRequest } from './models/CreatePromocionRequest';
export type { CreateReembolsoRequest } from './models/CreateReembolsoRequest';
export type { CreateUsuarioRequest } from './models/CreateUsuarioRequest';
export type { CreateVentaPagoRequest } from './models/CreateVentaPagoRequest';
export type { CreateVentaRequest } from './models/CreateVentaRequest';
export type { CuponesDePromocionListItem } from './models/CuponesDePromocionListItem';
export type { CuponesDePromocionListResponse } from './models/CuponesDePromocionListResponse';
export type { DeleteActividadHorarioUbicacionRequest } from './models/DeleteActividadHorarioUbicacionRequest';
export type { DeleteActividadPorZonaRequest } from './models/DeleteActividadPorZonaRequest';
export type { DeleteActividadRequest } from './models/DeleteActividadRequest';
export type { DeleteApartadoBoletoDestinatarioRequest } from './models/DeleteApartadoBoletoDestinatarioRequest';
export type { DeleteApartadoDeBoletoRequest } from './models/DeleteApartadoDeBoletoRequest';
export type { DeleteArticuloAdicionalRequest } from './models/DeleteArticuloAdicionalRequest';
export type { DeleteAsientoRequest } from './models/DeleteAsientoRequest';
export type { DeleteBoletoRequest } from './models/DeleteBoletoRequest';
export type { DeleteCarritoAdicionalRequest } from './models/DeleteCarritoAdicionalRequest';
export type { DeleteCarritoDeCompraRequest } from './models/DeleteCarritoDeCompraRequest';
export type { DeleteCarritoDeDetalleRequest } from './models/DeleteCarritoDeDetalleRequest';
export type { DeleteCuponDePromocionRequest } from './models/DeleteCuponDePromocionRequest';
export type { DeleteEventoRequest } from './models/DeleteEventoRequest';
export type { DeleteMesaRequest } from './models/DeleteMesaRequest';
export type { DeletePrecioDeBoletoRequest } from './models/DeletePrecioDeBoletoRequest';
export type { DeletePromocionRequest } from './models/DeletePromocionRequest';
export type { DeleteReembolsoRequest } from './models/DeleteReembolsoRequest';
export type { DeleteUsuarioRequest } from './models/DeleteUsuarioRequest';
export type { DeleteVentaRequest } from './models/DeleteVentaRequest';
export type { DominiosListItem } from './models/DominiosListItem';
export type { DominiosListResponse } from './models/DominiosListResponse';
export type { EditActividadHorarioUbicacionRequest } from './models/EditActividadHorarioUbicacionRequest';
export type { EditActividadPorZonaRequest } from './models/EditActividadPorZonaRequest';
export type { EditActividadRequest } from './models/EditActividadRequest';
export type { EditApartadoBoletoDestinatarioRequest } from './models/EditApartadoBoletoDestinatarioRequest';
export type { EditArticuloAdicionalRequest } from './models/EditArticuloAdicionalRequest';
export type { EditAsientoRequest } from './models/EditAsientoRequest';
export type { EditBoletoRequest } from './models/EditBoletoRequest';
export type { EditCarritoAdicionalRequest } from './models/EditCarritoAdicionalRequest';
export type { EditCarritoDeCompraRequest } from './models/EditCarritoDeCompraRequest';
export type { EditCarritoDeDetalleRequest } from './models/EditCarritoDeDetalleRequest';
export type { EditCuponDePromocionRequest } from './models/EditCuponDePromocionRequest';
export type { EditEventoRequest } from './models/EditEventoRequest';
export type { EditMesaRequest } from './models/EditMesaRequest';
export type { EditPrecioDeBoletoRequest } from './models/EditPrecioDeBoletoRequest';
export type { EditPromocionRequest } from './models/EditPromocionRequest';
export type { EditUsuarioRequest } from './models/EditUsuarioRequest';
export type { EditVentaRequest } from './models/EditVentaRequest';
export type { ErrorDescription } from './models/ErrorDescription';
export type { ErrorDetail } from './models/ErrorDetail';
export type { EstadosDeBoletoListItem } from './models/EstadosDeBoletoListItem';
export type { EstadosDeBoletoListResponse } from './models/EstadosDeBoletoListResponse';
export type { EstadosDePagoListItem } from './models/EstadosDePagoListItem';
export type { EstadosDePagoListResponse } from './models/EstadosDePagoListResponse';
export type { EstadosDeVentaListItem } from './models/EstadosDeVentaListItem';
export type { EstadosDeVentaListResponse } from './models/EstadosDeVentaListResponse';
export type { EventosListItem } from './models/EventosListItem';
export type { EventosListResponse } from './models/EventosListResponse';
export type { FormasDePagoListItem } from './models/FormasDePagoListItem';
export type { FormasDePagoListResponse } from './models/FormasDePagoListResponse';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { MesasListItem } from './models/MesasListItem';
export type { MesasListResponse } from './models/MesasListResponse';
export type { MotivosDeCancelacionListItem } from './models/MotivosDeCancelacionListItem';
export type { MotivosDeCancelacionListResponse } from './models/MotivosDeCancelacionListResponse';
export type { PreciosDeBoletoListItem } from './models/PreciosDeBoletoListItem';
export type { PreciosDeBoletoListResponse } from './models/PreciosDeBoletoListResponse';
export type { PromocionesListItem } from './models/PromocionesListItem';
export type { PromocionesListResponse } from './models/PromocionesListResponse';
export type { ReembolsosListItem } from './models/ReembolsosListItem';
export type { ReembolsosListResponse } from './models/ReembolsosListResponse';
export type { SearchResultList } from './models/SearchResultList';
export type { SelectListItem } from './models/SelectListItem';
export type { TiposDeBoletoListItem } from './models/TiposDeBoletoListItem';
export type { TiposDeBoletoListResponse } from './models/TiposDeBoletoListResponse';
export type { TiposDeDescuentoListItem } from './models/TiposDeDescuentoListItem';
export type { TiposDeDescuentoListResponse } from './models/TiposDeDescuentoListResponse';
export type { TiposDeDistribucionListItem } from './models/TiposDeDistribucionListItem';
export type { TiposDeDistribucionListResponse } from './models/TiposDeDistribucionListResponse';
export type { UbicacionesListItem } from './models/UbicacionesListItem';
export type { UbicacionesListResponse } from './models/UbicacionesListResponse';
export type { UsuariosListItem } from './models/UsuariosListItem';
export type { UsuariosListResponse } from './models/UsuariosListResponse';
export type { ValidationSummary } from './models/ValidationSummary';
export type { VentasListItem } from './models/VentasListItem';
export type { VentasListResponse } from './models/VentasListResponse';
export type { VentasPagoListItem } from './models/VentasPagoListItem';
export type { VentasPagoListResponse } from './models/VentasPagoListResponse';
export type { ZonasListItem } from './models/ZonasListItem';
export type { ZonasListResponse } from './models/ZonasListResponse';

export { ActividadesService } from './services/ActividadesService';
export { ActividadesHorarioUbicacionService } from './services/ActividadesHorarioUbicacionService';
export { ActividadesPorZonaService } from './services/ActividadesPorZonaService';
export { ApartadosBoletoDestinatarioService } from './services/ApartadosBoletoDestinatarioService';
export { ApartadosDeBoletoService } from './services/ApartadosDeBoletoService';
export { ArticulosAdicionalService } from './services/ArticulosAdicionalService';
export { AsientosService } from './services/AsientosService';
export { AuthService } from './services/AuthService';
export { BoletosService } from './services/BoletosService';
export { CanalesDeVentaService } from './services/CanalesDeVentaService';
export { CarritosAdicionalService } from './services/CarritosAdicionalService';
export { CarritosDeCompraService } from './services/CarritosDeCompraService';
export { CarritosDeDetalleService } from './services/CarritosDeDetalleService';
export { CuponesDePromocionService } from './services/CuponesDePromocionService';
export { DominiosService } from './services/DominiosService';
export { EstadosDeBoletoService } from './services/EstadosDeBoletoService';
export { EstadosDePagoService } from './services/EstadosDePagoService';
export { EstadosDeVentaService } from './services/EstadosDeVentaService';
export { EventosService } from './services/EventosService';
export { FormasDePagoService } from './services/FormasDePagoService';
export { MesasService } from './services/MesasService';
export { MotivosDeCancelacionService } from './services/MotivosDeCancelacionService';
export { PreciosDeBoletoService } from './services/PreciosDeBoletoService';
export { PromocionesService } from './services/PromocionesService';
export { ReembolsosService } from './services/ReembolsosService';
export { TiposDeBoletoService } from './services/TiposDeBoletoService';
export { TiposDeDescuentoService } from './services/TiposDeDescuentoService';
export { TiposDeDistribucionService } from './services/TiposDeDistribucionService';
export { UbicacionesService } from './services/UbicacionesService';
export { UsuariosService } from './services/UsuariosService';
export { VentasService } from './services/VentasService';
export { VentasPagoService } from './services/VentasPagoService';
export { ZonasService } from './services/ZonasService';
